# Generated by Django 5.2.16 on 2026-07-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='项目名称')),
                ('slug', models.SlugField(help_text='用于项目详情页地址，请使用英文字母、数字、连字符或下划线。', max_length=200, unique=True, verbose_name='URL 标识')),
                ('summary', models.CharField(max_length=500, verbose_name='项目简介')),
                ('description', models.TextField(verbose_name='详细介绍')),
                ('tech_stack', models.TextField(help_text='简要说明项目使用的语言、框架和工具。', verbose_name='技术栈')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub 地址')),
                ('demo_url', models.URLField(blank=True, verbose_name='在线演示地址')),
                ('status', models.CharField(choices=[('developing', '开发中'), ('completed', '已完成'), ('maintaining', '维护中')], db_index=True, default='developing', max_length=12, verbose_name='项目状态')),
                ('featured', models.BooleanField(db_index=True, default=False, verbose_name='精选项目')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-featured', '-updated_at', '-created_at'],
            },
        ),
    ]
