# Generated by Django 5.2.16 on 2026-07-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('role', models.CharField(max_length=200, verbose_name='个人定位')),
                ('direction', models.CharField(max_length=300, verbose_name='技术方向')),
                ('introduction', models.TextField(verbose_name='个人简介')),
                ('education', models.CharField(max_length=300, verbose_name='教育背景')),
                ('education_detail', models.TextField(verbose_name='教育背景说明')),
                ('courses', models.TextField(help_text='每行填写一项。', verbose_name='主修课程')),
                ('experience_highlight', models.TextField(verbose_name='实践亮点')),
                ('learning_topics', models.TextField(help_text='每行填写一项。', verbose_name='当前学习方向')),
                ('skills', models.TextField(help_text='每行填写一项。', verbose_name='技术能力')),
                ('languages', models.TextField(help_text='每行填写一项。', verbose_name='语言能力')),
                ('interests', models.TextField(help_text='每行填写一项。', verbose_name='兴趣爱好')),
                ('career_goal', models.TextField(verbose_name='求职目标')),
                ('project_goal', models.TextField(verbose_name='平台建设目标')),
            ],
            options={
                'verbose_name': '关于我内容',
                'verbose_name_plural': '关于我内容',
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('role', models.CharField(max_length=200, verbose_name='个人定位')),
                ('direction', models.CharField(max_length=300, verbose_name='技术方向')),
                ('introduction', models.TextField(verbose_name='个人简介')),
                ('career_goal', models.TextField(verbose_name='求职目标')),
            ],
            options={
                'verbose_name': '首页内容',
                'verbose_name_plural': '首页内容',
            },
        ),
    ]
