# Generated by Django 5.2.16 on 2026-07-23 05:52

import django.core.validators
import django.db.models.deletion
import social.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(choices=[('personal', '个人主页'), ('circle', '圈')], db_index=True, max_length=10, verbose_name='动态类型')),
                ('content', models.TextField(blank=True, max_length=2000, verbose_name='文字内容')),
                ('image', models.ImageField(blank=True, upload_to=social.models.social_image_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), social.models.validate_image_upload], verbose_name='图片')),
                ('video', models.FileField(blank=True, upload_to=social.models.social_video_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm']), social.models.validate_video_upload], verbose_name='视频')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '社交动态',
                'verbose_name_plural': '社交动态',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SocialLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_likes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.socialpost', verbose_name='动态')),
            ],
            options={
                'verbose_name': '社交点赞',
                'verbose_name_plural': '社交点赞',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SocialComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_comments', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.socialpost', verbose_name='动态')),
            ],
            options={
                'verbose_name': '社交评论',
                'verbose_name_plural': '社交评论',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['feed_type', '-created_at'], name='social_feed_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialpost',
            constraint=models.CheckConstraint(condition=models.Q(('image', ''), ('video', ''), _connector='OR'), name='social_post_single_media'),
        ),
        migrations.AddConstraint(
            model_name='socialpost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('content', ''), _negated=True), models.Q(('image', ''), _negated=True), models.Q(('video', ''), _negated=True), _connector='OR'), name='social_post_has_content'),
        ),
        migrations.AddConstraint(
            model_name='sociallike',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_social_like'),
        ),
        migrations.AddIndex(
            model_name='socialcomment',
            index=models.Index(fields=['post', 'created_at'], name='social_comment_created_idx'),
        ),
    ]
